/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.MainUI.mainGraph;
import OrganizedChaos.Product;
import OrganizedChaos.Vertex;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class AddProductUI extends javax.swing.JFrame {
    
    public static WarehouseStockManagerUI warehouseStockManager;
    public static String sWarehouseName;

    /**
     * Creates new form OrderUI
     * @param warehouseStockManager
     * @param sWarehouseName
     */
    public AddProductUI(WarehouseStockManagerUI warehouseStockManager, String sWarehouseName) {
        initComponents();
        this.warehouseStockManager = warehouseStockManager;
        this.sWarehouseName = sWarehouseName;
        warehouseStockManager.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionar_label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        quantityToAdd = new javax.swing.JTextField();
        EnterName_label = new javax.swing.JLabel();
        addProduct = new javax.swing.JButton();
        gestionar_label1 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        EnterName_label1 = new javax.swing.JLabel();
        EnterName_label2 = new javax.swing.JLabel();
        EnterName_label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionar_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestionar_label.setText("DEL ALMACÉN");
        jPanel1.add(gestionar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, 30));

        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 30));

        quantityToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityToAddActionPerformed(evt);
            }
        });
        jPanel1.add(quantityToAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 220, 30));

        EnterName_label.setText(" existente en el inventario)");
        jPanel1.add(EnterName_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, 20));

        addProduct.setText("Añadir");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });
        jPanel1.add(addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, 40));

        gestionar_label1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestionar_label1.setText("AÑADIR A UN PRODUCTO EXISTENTE");
        jPanel1.add(gestionar_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 410, 40));

        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, 30));

        EnterName_label1.setText("Introduzca el nombre del producto");
        jPanel1.add(EnterName_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        EnterName_label2.setText("Introduzca la cantidad a aumentar");
        jPanel1.add(EnterName_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 200, -1));

        EnterName_label3.setText("(Esta cantidad se sumará a la cantidad");
        jPanel1.add(EnterName_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        warehouseStockManager.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void quantityToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityToAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityToAddActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        String sProductName = productName.getText();
        String sQuantityToAdd = quantityToAdd.getText();
        
        try {
            Vertex warehouse = mainGraph.getVert(sWarehouseName);
            if("".equals(sProductName) || "".equals(sQuantityToAdd)) {
                JOptionPane.showMessageDialog(null, "Debe agregar el nombre del producto y su cantidad");
            } else {
                int iQuantityToAdd = Integer.parseInt(sQuantityToAdd);
                
               if(iQuantityToAdd < 0) {
                   JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad positiva");
               } else {
                   
                   if (warehouse.getProduct(sProductName) != null) {
                       
                       JOptionPane.showMessageDialog(null, "Se ha encontrado el producto!");

                       Product product = warehouse.getProduct(sProductName);
                       product.setQuantity(product.getQuantity() + iQuantityToAdd);
                       JOptionPane.showMessageDialog(null, "El producto ha sido aumentado con éxito!");
                       
                   } else {
                       JOptionPane.showMessageDialog(null, "No se ha encontrado el producto");
                   }
               }
            }
                
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error: " + e);
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductUI(warehouseStockManager, sWarehouseName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterName_label;
    private javax.swing.JLabel EnterName_label1;
    private javax.swing.JLabel EnterName_label2;
    private javax.swing.JLabel EnterName_label3;
    private javax.swing.JButton addProduct;
    private javax.swing.JButton back;
    private javax.swing.JLabel gestionar_label;
    private javax.swing.JLabel gestionar_label1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField quantityToAdd;
    // End of variables declaration//GEN-END:variables
}
