/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.MainUI.mainGraph;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class addWarehouseUI extends javax.swing.JFrame {
    
    public static WarehouseManagerUI warehouseManager;
    /**
     * Creates new form addWarehouseUI
     */
    public addWarehouseUI(WarehouseManagerUI warehouseManager) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.warehouseManager = warehouseManager;
        warehouseManager.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionar_label = new javax.swing.JLabel();
        warehouseName = new javax.swing.JTextField();
        addWarehouse_label = new javax.swing.JLabel();
        addWarehouse = new javax.swing.JButton();
        back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionar_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestionar_label.setText("AÑADIR UN ALMACÉN");
        jPanel1.add(gestionar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 250, 50));

        warehouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseNameActionPerformed(evt);
            }
        });
        jPanel1.add(warehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, 30));

        addWarehouse_label.setText("Ingresa el nombre del almacén");
        jPanel1.add(addWarehouse_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        addWarehouse.setText("Añadir");
        addWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWarehouseActionPerformed(evt);
            }
        });
        jPanel1.add(addWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 90, 30));

        back1.setText("Volver");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void warehouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseNameActionPerformed

    private void addWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWarehouseActionPerformed
        
        
        try {
            String sWarehouseName = warehouseName.getText();
            mainGraph.newVert(sWarehouseName);
            JOptionPane.showMessageDialog(null,"Se ha añadido el almacén con éxito!");
            addWarehouseArchUI ways = new addWarehouseArchUI(this, sWarehouseName);
                        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Se produjo un error. Introduzca el nombre del almacén.  " + e);
        }
    }//GEN-LAST:event_addWarehouseActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        this.setVisible(false);
        warehouseManager.setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addWarehouseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addWarehouseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addWarehouseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addWarehouseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addWarehouseUI(warehouseManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWarehouse;
    private javax.swing.JLabel addWarehouse_label;
    private javax.swing.JButton back1;
    private javax.swing.JLabel gestionar_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField warehouseName;
    // End of variables declaration//GEN-END:variables
}
