/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.MainUI.mainGraph;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class newArchUI extends javax.swing.JFrame {
    
    public static WarehouseManagerUI warehouseManager;
    /**
     * Creates new form addWarehouseUI
     */
    public newArchUI(WarehouseManagerUI warehouseManager) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.warehouseManager = warehouseManager;
        warehouseManager.setVisible(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionar_label = new javax.swing.JLabel();
        destiny = new javax.swing.JTextField();
        Hola2 = new javax.swing.JLabel();
        addArch = new javax.swing.JButton();
        origin = new javax.swing.JTextField();
        origin_label1 = new javax.swing.JLabel();
        origin_label2 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionar_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestionar_label.setText("AGREGAR CAMINO A ALMACENES EXISTENTES");
        jPanel1.add(gestionar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 510, 50));

        destiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinyActionPerformed(evt);
            }
        });
        jPanel1.add(destiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 260, 30));

        Hola2.setText("Nombre del almacén destino");
        jPanel1.add(Hola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 170, 20));

        addArch.setText("Añadir camino");
        addArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArchActionPerformed(evt);
            }
        });
        jPanel1.add(addArch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 130, 40));

        origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originActionPerformed(evt);
            }
        });
        jPanel1.add(origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 260, 30));

        origin_label1.setText("Nombre del almacén origen");
        jPanel1.add(origin_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 20));

        origin_label2.setText("Distancia entre los dos almacenes");
        jPanel1.add(origin_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 210, 20));

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        jPanel1.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 30));

        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinyActionPerformed

    private void addArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArchActionPerformed
            String sOrigin = origin.getText();
            String sDestiny = destiny.getText();
            String sValue = value.getText();
            
        try {

            if ("".equals(sOrigin) || "".equals(sDestiny) ||  "".equals(sValue)) {
                JOptionPane.showMessageDialog(null, "Debe agregar los nombres de los almacenes origenes, destino y la distancia numéricamente para crear el camino");
            } else {
                int vValue = Integer.parseInt(sValue);
                if(vValue < 0) {
                    JOptionPane.showMessageDialog(null, "Debe ingresar distancias positivas. ");
                } else {
                    mainGraph.newArch(sOrigin, sDestiny, vValue);
                    JOptionPane.showMessageDialog(null, "Se han agregado los caminos con éxito!");
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error: " + e);
        }
        
    }//GEN-LAST:event_addArchActionPerformed

    private void originActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        warehouseManager.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newArchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newArchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newArchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newArchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newArchUI(warehouseManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hola2;
    private javax.swing.JButton addArch;
    private javax.swing.JButton back;
    private javax.swing.JTextField destiny;
    private javax.swing.JLabel gestionar_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField origin;
    private javax.swing.JLabel origin_label1;
    private javax.swing.JLabel origin_label2;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
