/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.MainUI.mainGraph;
import OrganizedChaos.Vertex;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class WarehouseStockManagerUI extends javax.swing.JFrame {
    
    public static WarehouseManagerUI v3;
    
    /**
     * Creates new form OrderUI
     */
    public WarehouseStockManagerUI(WarehouseManagerUI v3) {
        initComponents();
        this.v3 = v3;
        v3.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionar_label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        addExistingProduct = new javax.swing.JButton();
        warehouseName = new javax.swing.JTextField();
        stockWarehouse_label = new javax.swing.JLabel();
        update2_label = new javax.swing.JLabel();
        choose1 = new javax.swing.JButton();
        addNewProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        warehouseStock = new javax.swing.JTextArea();
        EnterName_label1 = new javax.swing.JLabel();
        update_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionar_label.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        gestionar_label.setForeground(new java.awt.Color(255, 255, 153));
        gestionar_label.setText("GESTIÓN DE INVENTARIOS");
        jPanel1.add(gestionar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 340, 50));

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 30));

        addExistingProduct.setBackground(new java.awt.Color(255, 255, 153));
        addExistingProduct.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        addExistingProduct.setForeground(new java.awt.Color(51, 51, 51));
        addExistingProduct.setText("Añadir a producto existente");
        addExistingProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExistingProductActionPerformed(evt);
            }
        });
        jPanel1.add(addExistingProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 210, 30));

        warehouseName.setBackground(new java.awt.Color(102, 102, 102));
        warehouseName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        warehouseName.setForeground(new java.awt.Color(255, 255, 255));
        warehouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseNameActionPerformed(evt);
            }
        });
        jPanel1.add(warehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 30));

        stockWarehouse_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        stockWarehouse_label.setForeground(new java.awt.Color(255, 255, 153));
        stockWarehouse_label.setText("Inventario del almacén:");
        jPanel1.add(stockWarehouse_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 20));

        update2_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        update2_label.setForeground(new java.awt.Color(255, 255, 153));
        update2_label.setText("actualizar el Inventario mostrado");
        jPanel1.add(update2_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 220, 10));

        choose1.setBackground(new java.awt.Color(255, 255, 153));
        choose1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        choose1.setForeground(new java.awt.Color(51, 51, 51));
        choose1.setText("Escoger");
        choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose1ActionPerformed(evt);
            }
        });
        jPanel1.add(choose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        addNewProduct.setBackground(new java.awt.Color(255, 255, 153));
        addNewProduct.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        addNewProduct.setForeground(new java.awt.Color(51, 51, 51));
        addNewProduct.setText("Agregar nuevo producto");
        addNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProductActionPerformed(evt);
            }
        });
        jPanel1.add(addNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, 30));

        warehouseStock.setBackground(new java.awt.Color(102, 102, 102));
        warehouseStock.setColumns(20);
        warehouseStock.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        warehouseStock.setForeground(new java.awt.Color(255, 255, 255));
        warehouseStock.setRows(5);
        jScrollPane2.setViewportView(warehouseStock);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 170));

        EnterName_label1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        EnterName_label1.setForeground(new java.awt.Color(255, 255, 153));
        EnterName_label1.setText("Introduzca el nombre de un almacén");
        jPanel1.add(EnterName_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        update_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        update_label.setForeground(new java.awt.Color(255, 255, 153));
        update_label.setText("Debe darle al botón para ");
        jPanel1.add(update_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        v3.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void warehouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseNameActionPerformed

    private void choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose1ActionPerformed
        String sWarehouseName = warehouseName.getText();
        
        Vertex warehouse = mainGraph.getVert(sWarehouseName);
        
        if(warehouse != null) {
            JOptionPane.showMessageDialog(null, "El almacén se ha encontrado con éxito!");
            warehouseStock.setText(warehouse.printStock());
        } else {
            JOptionPane.showMessageDialog(null, "El almacén no se ha encontrado");
        } 
    }//GEN-LAST:event_choose1ActionPerformed

    private void addNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProductActionPerformed
       String sWarehouseName = warehouseName.getText();
       
       Vertex warehouse = mainGraph.getVert(sWarehouseName);
        
        if(warehouse != null) {
            
            AddNewProductUI newProduct = new AddNewProductUI(this, sWarehouseName);
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un almacén primero");
        } 
    }//GEN-LAST:event_addNewProductActionPerformed

    private void addExistingProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExistingProductActionPerformed
        String sWarehouseName = warehouseName.getText();
       
        Vertex warehouse = mainGraph.getVert(sWarehouseName);
        
        if(warehouse != null) {
            AddProductUI existingProduct = new AddProductUI(this, sWarehouseName);
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un almacén primero");
        } 
    }//GEN-LAST:event_addExistingProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseStockManagerUI(v3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterName_label1;
    private javax.swing.JButton addExistingProduct;
    private javax.swing.JButton addNewProduct;
    private javax.swing.JButton back;
    private javax.swing.JButton choose1;
    private javax.swing.JLabel gestionar_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel stockWarehouse_label;
    private javax.swing.JLabel update2_label;
    private javax.swing.JLabel update_label;
    private javax.swing.JTextField warehouseName;
    private javax.swing.JTextArea warehouseStock;
    // End of variables declaration//GEN-END:variables
}
