/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Rolando
 */
public class WarehouseStockManagerUI extends javax.swing.JFrame {
    
    public static WarehouseManagerUI v3;
    
    /**
     * Creates new form OrderUI
     */
    public WarehouseStockManagerUI(WarehouseManagerUI v3) {
        initComponents();
        this.v3 = v3;
        v3.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionar_label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        addExistingProduct = new javax.swing.JButton();
        warehouseName = new javax.swing.JTextField();
        stockWarehouse_label = new javax.swing.JLabel();
        EnterName_label = new javax.swing.JLabel();
        choose1 = new javax.swing.JButton();
        addNewProduct = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        warehouseStock = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionar_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestionar_label.setText("GESTIÓN DE INVENTARIOS");
        jPanel1.add(gestionar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 50));

        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 30));

        addExistingProduct.setText("Añadir a producto existente");
        jPanel1.add(addExistingProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 190, 30));

        warehouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseNameActionPerformed(evt);
            }
        });
        jPanel1.add(warehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 30));

        stockWarehouse_label.setText("Inventario del almacén:");
        jPanel1.add(stockWarehouse_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        EnterName_label.setText("Introduzca el nombre de un almacén");
        jPanel1.add(EnterName_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        choose1.setText("Escoger");
        jPanel1.add(choose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        addNewProduct.setText("Agregar nuevo producto");
        jPanel1.add(addNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 190, 30));

        warehouseStock.setColumns(20);
        warehouseStock.setRows(5);
        jScrollPane2.setViewportView(warehouseStock);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        v3.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void warehouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehouseNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseStockManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseStockManagerUI(v3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterName_label;
    private javax.swing.JButton addExistingProduct;
    private javax.swing.JButton addNewProduct;
    private javax.swing.JButton back;
    private javax.swing.JButton choose1;
    private javax.swing.JLabel gestionar_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel stockWarehouse_label;
    private javax.swing.JTextField warehouseName;
    private javax.swing.JTextArea warehouseStock;
    // End of variables declaration//GEN-END:variables
}
